# Name: Sartaj singh, Navjot singh
# Date: 2024-07-28
# Modified: 2024-07-28
# Descrption: Website to purchase clothes using selenium 

# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains

DELAY = 1


class TestSartajNavjot:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_sartajNavjot(self):
        self.driver.get("https://magento.softwaretestingboard.com/")
        self.driver.set_window_size(1844, 1415)
        time.sleep(DELAY)

        element = self.driver.find_element(By.ID, "ui-id-4")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        time.sleep(DELAY)

        element = self.driver.find_element(By.ID, "ui-id-9")
        actions.move_to_element(element).perform()
        time.sleep(DELAY)

        self.driver.find_element(By.ID, "ui-id-12").click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".filter-options-item:nth-child(1) > .filter-options-title"
        ).click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".allow .item:nth-child(3) > a"
        ).click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".filter-options-item:nth-child(1) > .filter-options-title"
        ).click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".swatch-option-link-layered:nth-child(3) > .text"
        ).click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".filter-options-item:nth-child(2) > .filter-options-title"
        ).click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".swatch-option-link-layered:nth-child(1) > .swatch-option"
        ).click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".filter-options-item:nth-child(4) > .filter-options-title"
        ).click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".active .item:nth-child(4) > a"
        ).click()
        time.sleep(DELAY)

        element = self.driver.find_element(By.CSS_SELECTOR, ".product-item-info")
        actions.move_to_element(element).perform()
        time.sleep(DELAY)

        self.driver.find_element(By.CSS_SELECTOR, ".tocart > span").click()
        time.sleep(DELAY)

        element = self.driver.find_element(By.ID, "ui-id-5")
        actions.move_to_element(element).perform()
        time.sleep(DELAY)

        element = self.driver.find_element(By.ID, "ui-id-17")
        actions.move_to_element(element).perform()
        time.sleep(DELAY)

        self.driver.find_element(By.CSS_SELECTOR, "#ui-id-20 > span").click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".filter-options-item:nth-child(1) > .filter-options-title"
        ).click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".swatch-option-link-layered:nth-child(3) > .text"
        ).click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".filter-options-item:nth-child(9) > .filter-options-title"
        ).click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".item:nth-child(2) .price:nth-child(2)"
        ).click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".filter-options-item:nth-child(2) > .filter-options-title"
        ).click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".swatch-option-link-layered:nth-child(1) > .swatch-option"
        ).click()
        time.sleep(DELAY)

        self.driver.execute_script("window.scrollTo(0,92)")
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".filter-options-item:nth-child(4) > .filter-options-title"
        ).click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".active .item:nth-child(3) > a"
        ).click()
        time.sleep(DELAY)

        element = self.driver.find_element(By.CSS_SELECTOR, ".product-item-info")
        actions.move_to_element(element).perform()
        time.sleep(DELAY)

        self.driver.find_element(By.CSS_SELECTOR, ".tocart > span").click()
        time.sleep(DELAY)

        element = self.driver.find_element(By.ID, "ui-id-5")
        actions.move_to_element(element).perform()
        time.sleep(DELAY)

        element = self.driver.find_element(By.ID, "ui-id-17")
        actions.move_to_element(element).perform()
        time.sleep(DELAY)

        self.driver.find_element(By.ID, "ui-id-19").click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".filter-options-item:nth-child(2) > .filter-options-title"
        ).click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".swatch-option-link-layered:nth-child(3) > .text"
        ).click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR,
            ".filter-options-item:nth-child(10) > .filter-options-title",
        ).click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".item:nth-child(2) .price:nth-child(2)"
        ).click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".filter-options-item:nth-child(3) > .filter-options-title"
        ).click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".swatch-option-link-layered:nth-child(2) > .swatch-option"
        ).click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".filter-options-item:nth-child(5) > .filter-options-title"
        ).click()
        time.sleep(DELAY)

        self.driver.find_element(
            By.CSS_SELECTOR, ".active .item:nth-child(5) > a"
        ).click()
        time.sleep(DELAY)

        element = self.driver.find_element(By.CSS_SELECTOR, ".product-item-info")
        actions.move_to_element(element).perform()
        time.sleep(DELAY)

        self.driver.find_element(By.CSS_SELECTOR, ".tocart > span").click()
        time.sleep(DELAY)

        self.driver.find_element(By.CSS_SELECTOR, ".showcart").click()
        time.sleep(DELAY)

        self.driver.find_element(By.ID, "top-cart-btn-checkout").click()
        time.sleep(DELAY)


if __name__ == "__main__":
    pytest.main(["-v", "test_sartajNavjot.py"])
