# Name: Navjot Singh
# Student ID: 100931376
# Date: July 19, 2024
# Modified: July 19, 2024
# Description: Creating a python script with Selenium to login on a website.
# Generated by Selenium IDE

# Import Packages
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestcase2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()

  # Open the login Page.
  def test_testcase2(self):
    self.driver.get("https://demo.guru99.com/test/newtours/")
    self.driver.set_window_size(1382, 736)

    # Fill the user name.
    self.driver.find_element(By.NAME, "userName").click()
    self.driver.find_element(By.NAME, "userName").send_keys("navjotsingh57")

    # Fill the Password.
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("Navkaran13a~")

    # Click Submit Option.
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5)").click()
  
