# Name: Navjot Singh
# Student ID: 100931376
# Date: July 19, 2024
# Modified: July 19, 2024
# Description: Creating a python script with Selenium to register on a website.
# Generated by Selenium IDE

# Import Packages
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestcase1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()

  # Open the registration form.
  def test_testcase1(self):
    self.driver.get("https://demo.guru99.com/test/newtours/register.php")
    self.driver.set_window_size(1382, 736)

    # Filling Registration Form.
    self.driver.find_element(By.NAME, "firstName").click()
    self.driver.find_element(By.NAME, "firstName").send_keys("Navjot")

    self.driver.find_element(By.NAME, "lastName").click()
    self.driver.find_element(By.NAME, "lastName").send_keys("Singh")

    self.driver.find_element(By.NAME, "phone").click()
    self.driver.find_element(By.NAME, "phone").send_keys("4376071093")

    self.driver.find_element(By.ID, "userName").click()
    self.driver.find_element(By.ID, "userName").send_keys("jotsandhu13a@gmail.com")

    self.driver.find_element(By.NAME, "address1").click()
    self.driver.find_element(By.NAME, "address1").send_keys("3086 Morning Star")

    self.driver.find_element(By.NAME, "city").click()
    self.driver.find_element(By.NAME, "city").send_keys("Mississauga")

    self.driver.find_element(By.NAME, "state").click()
    self.driver.find_element(By.NAME, "state").send_keys("Ontario")

    self.driver.find_element(By.NAME, "postalCode").click()
    self.driver.find_element(By.NAME, "postalCode").send_keys("L4T 1X2")

    # Selecting Country from options.
    self.driver.find_element(By.NAME, "country").click()
    dropdown = self.driver.find_element(By.NAME, "country")
    dropdown.find_element(By.XPATH, "//option[. = 'CANADA']").click()

    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("navjotsingh57")

    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("Navkaran13a~")

    self.driver.find_element(By.NAME, "confirmPassword").click()
    self.driver.find_element(By.NAME, "confirmPassword").send_keys("Navkaran13a~")

    # At Last, Submit the form.
    self.driver.find_element(By.NAME, "submit").click()
  
